---
title: "研究"
output:
  html_document:
    css: "style.css"
    self_contained: no
---

リハビリテーション医学・生体医工学に広く興味を持っています。  
特に歩行やADL動作などの身体運動の面から健康寿命の延伸に寄与できるような研究ができれば研究ができればと思っています。

## 学術論文
  - 国際雑誌（筆頭・査読あり）
    1. <B><U>Kosuke Fujita</U></B>, Aiko Inoue, Masafumi Kuzuya, Chiharu Uno, Chi Hsien Huang, Hiroyuki Umegaki, Joji Onishi; Mental Health Status of the Older Adults in Japan During the COVID-19 Pandemic. J Am Med Dir Assoc. 2021 Jan;22(1):220-221. doi: [10.1016/j.jamda.2020.11.023.](https://www.jamda.com/article/S1525-8610(20)30988-9/fulltext)
    
    
    1. <B><U>Kosuke Fujita</U></B>, Hirotaka Nakashima, Masato Kako, Atsushi Shibata, Cheng Yu-Ting, Shinya Tanaka, Yoshihiro Nishida, Masafumi Kuzuya; Short physical performance battery discriminates clinical outcomes in hospitalized patients aged 75 years and over. Arch Gerontol Geriatr. Sep-Oct 2020;90:104155. doi: [10.1016/j.archger.2020.104155.](https://www.sciencedirect.com/science/article/abs/pii/S0167494320301497?via%3Dihub)
    1. <B><U>Kosuke Fujita</U></B>, Masatoshi Nakamura, Hiroki Umegaki, Takuya Kobayashi, Satoru Nishishita, Hiroki Tanaka, Satoko Ibuki, Noriaki Ichihashi; Effects of a Thermal Agent and Physical Activity on Muscle Tendon Stiffness, as Well as the Effects Combined With Static Stretching. J Sport Rehabil. 2018 Jan 1;27(1):66-72. doi: [10.1123/jsr.2015-0165.](https://journals.humankinetics.com/view/journals/jsr/27/1/article-p66.xml?content=abstract)

  - 国際雑誌（共著・査読あり）
    1. Sayaka Nakao, Tome Ikezoe, Masatoshi Nakamura, Hiroki Umegaki, <B><U>Kosuke Fujita</U></B>, Jun Umehara, Takuya Kobayashi, Satoko Ibuki, Noriaki Ichihashi; Chronic Effects of a Static Stretching Program on Hamstring Strength. J Strength Cond Res. 2019 Jan 23. doi: [10.1519/JSC.0000000000003037.](https://journals.lww.com/nsca-jscr/Abstract/9000/Chronic_Effects_of_a_Static_Stretching_Program_on.94986.aspx)
    
    
    1. Junya Saeki, Masatoshi Nakamura, Sayaka Nakao, <B><U>Kosuke Fujita</U></B>, Ko Yanase, Katsuyuki Morishita, Noriaki Ichihashi; Ankle and toe muscle strength characteristics in runners with a history of medial tibial stress syndrome. J Foot Ankle Res. 2017 Apr 11;10:16. doi: [10.1186/s13047-017-0197-2.](https://jfootankleres.biomedcentral.com/articles/10.1186/s13047-017-0197-2)
    1. Ko Yanase, Satoshi Hasegawa, Masatoshi Nakamura, Taishi Yamauchi, Satoru Nishishita, Kojiro Araki, Jun Umehara, <B><U>Kosuke Fujita</U></B>, Ikuya Sato, Satoko Ibuki, Noriaki Ichihashi; Electrical Stimulation to the Infraspinatus on Hypertrophy and Strength of the Shoulder. Int J Sports Med. 2018 Oct;39(11):828-834. doi: [10.1055/s-0044-102129.](https://www.thieme-connect.de/products/ejournals/abstract/10.1055/s-0044-102129)
    1. Taishi Yamauchi, Satoshi Hasegawa, Masatoshi Nakamura, Satoru Nishishita, Ko Yanase, <B><U>Kosuke Fujita</U></B>, Jun Umehara, Xiang Ji, Satoko Ibuki, Noriaki Ichihashi; Effects of two stretching methods on shoulder range of motion and muscle stiffness in baseball players with posterior shoulder tightness: a randomized controlled trial. J Shoulder Elbow Surg. 2016 Sep;25(9):1395-403. doi: [10.1016/j.jse.2016.04.025.](https://www.jshoulderelbow.org/)
    1. Hiroki Tanaka, Tome Ikezoe, Jun Umehara, Masatoshi Nakamura, Hiroki Umegaki, Takuya Kobayashi, Satoru Nishishita, <B><U>Kosuke Fujita</U></B>, Kojiro Araki, Noriaki Ichihashi; Influences of Fascicle Length During Isometric Training on Improvement of Muscle Strength. J Strength Cond Res. 2016 Nov;30(11):3249-3255. doi: [10.1519/JSC.0000000000001419.](https://journals.lww.com/nsca-jscr/Fulltext/2016/11000/Influences_of_Fascicle_Length_During_Isometric.35.aspx)
    1. Yumiko Koyama, Hiroshige Tateuchi, Koujiro Araki, <B><U>Kosuke Fujita</U></B>, Jun Umehara, Masashi Kobayashi, Noriaki Ichihashi; Mechanical energy efficiency for stepping up and down in persons with medial knee osteoarthritis. Gait Posture. 2019 Mar;69:143-149. doi: [10.1016/j.gaitpost.2019.01.009.](https://www.sciencedirect.com/science/article/abs/pii/S0966636219300268?via%3Dihub)
    1. Hiroki Tanaka, Tome Ikezoe, Masatoshi Nakamura, Ko Yanase, <B><U>Kosuke Fujita</U></B>, Yoshiki Motomura, Ken Kusano, Kojiro Araki, Jun Umehara, Junya Saeki, Katsuyuki Morishita, Noriaki Ichihashi; Improvement in muscle strength with low-load isotonic training depends on fascicle length but not joint angle. Muscle Nerve. 2018 Jan;57(1):83-89. doi: [10.1002/mus.25601.](https://onlinelibrary.wiley.com/doi/abs/10.1002/mus.25601)
    1. Jun Umehara, Masatoshi Nakamura, <B><U>Kosuke Fujita</U></B>, Ken Kusano, Satoru Nishishita, Kojiro Araki, Hiroki Tanaka, Ko Yanase, Noriaki Ichihashi; Shoulder horizontal abduction stretching effectively increases shear elastic modulus of pectoralis minor muscle. J Shoulder Elbow Surg. 2017 Jul;26(7):1159-1165. doi: [10.1016/j.jse.2016.12.074.](https://www.jshoulderelbow.org/article/S1058-2746(17)30018-6/fulltext)
    1. J Saeki, M Nakamura, S Nakao, <B><U>K Fujita</U></B>, K Yanase, N Ichihashi; Muscle stiffness of posterior lower leg in runners with a history of medial tibial stress syndrome. Scand J Med Sci Sports. 2018 Jan;28(1):246-251. doi: [10.1111/sms.12862.](https://onlinelibrary.wiley.com/doi/abs/10.1111/sms.12862)
    1. Noriaki Ichihashi, Hiroki Umegaki, Tome Ikezoe, Masatoshi Nakamura, Satoru Nishishita, <B><U>Kosuke Fujita</U></B>, Jun Umehara, Sayaka Nakao, Satoko Ibuki; The effects of a 4-week static stretching programme on the individual muscles comprising the hamstrings. J Sports Sci. 2016 Dec;34(23):2155-2159. doi: [10.1080/02640414.2016.1172725.](https://www.tandfonline.com/doi/abs/10.1080/02640414.2016.1172725?journalCode=rjsp20)
    1. Hiroki Umegaki, Tome Ikezoe, Masatoshi Nakamura, Satoru Nishishita, Takuya Kobayashi, <B><U>Kosuke Fujita</U></B>, Hiroki Tanaka, Noriaki Ichihashi; The effect of hip rotation on shear elastic modulus of the medial and lateral hamstrings during stretching. Man Ther. 2015 Feb;20(1):134-7. doi: [10.1016/j.math.2014.07.016.](https://www.sciencedirect.com/science/article/abs/pii/S1356689X14001465?via%3Dihub)
    1. Jun Umehara, Tome Ikezoe, Satoru Nishishita, Masatoshi Nakamura, Hiroki Umegaki, Takuya Kobayashi, <B><U>Kosuke Fujita</U></B>, Noriaki Ichihashi; Effect of hip and knee position on tensor fasciae latae elongation during stretching: An ultrasonic shear wave elastography study. Clin Biomech (Bristol, Avon). 2015 Dec;30(10):1056-9. doi: [10.1016/j.clinbiomech.2015.09.007.](https://www.clinbiomech.com/article/S0268-0033(15)00248-X/fulltext)
    1. Masatoshi Nakamura, Satoshi Hasegawa, Hiroki Umegaki, Satoru Nishishita, Takuya Kobayashi, <B><U>Kosuke Fujita</U></B>, Hiroki Tanaka, Satoko Ibuki, Noriaki Ichihashi; The difference in passive tension applied to the muscles composing the hamstrings - Comparison among muscles using ultrasound shear wave elastography. Man Ther. 2016 Aug;24:1-6. doi: [10.1016/j.math.2016.03.012.](https://www.sciencedirect.com/science/article/abs/pii/S1356689X16300029?via%3Dihub)
    1. Hiroki Umegaki, Tome Ikezoe, Masatoshi Nakamura, Satoru Nishishita, Takuya Kobayashi, <B><U>Kosuke Fujita</U></B>, Hiroki Tanaka, Noriaki Ichihashi; Acute effects of static stretching on the hamstrings using shear elastic modulus determined by ultrasound shear wave elastography: Differences in flexibility between hamstring muscle components. Man Ther. 2015 Aug;20(4):610-3. doi: [10.1016/j.math.2015.02.006.](https://www.sciencedirect.com/science/article/abs/pii/S1356689X15000247?via%3Dihub)
    1. Jun Umehara, Satoshi Hasegawa, Masatoshi Nakamura, Satoru Nishishita, Hiroki Umegaki, Hiroki Tanaka, <B><U>Kosuke Fujita</U></B>, Ken Kusano, Noriaki Ichihashi; Effect of scapular stabilization during cross-body stretch on the hardness of infraspinatus, teres minor, and deltoid muscles: An ultrasonic shear wave elastography study. Musculoskelet Sci Pract. 2017 Feb;27:91-96. doi: [10.1016/j.math.2016.10.004.](https://www.sciencedirect.com/science/article/abs/pii/S1356689X16307391?via%3Dihub)
    1. Jun Umehara, Masatoshi Nakamura, Junya Saeki, Hiroki Tanaka, Ko Yanase, <B><U>Kosuke Fujita</U></B>, Momoko Yamagata, Noriaki Ichihashi; Acute and Prolonged Effects of Stretching on Shear Modulus of the Pectoralis Minor Muscle. J Sports Sci Med. 2021 Mar 1;20(1):17-25. doi: [10.52082/jssm.2021.17.](https://www.jssm.org/jssm-20-17.xml%3EFulltext)

---

## 学術会議における発表
  - 国際会議
    1. 
    1. 
  - 国内学会
    1. 藤田 康介, 梅垣 宏行, 黄 継賢, 井上 愛子, 宇野 千晴, 葛谷 雅文; ベースラインでサルコペニアを有する高齢者は運動介入に対する治療反応性が乏しいのか?　TOPICS trialのsubgroup解析による検討. 第62回日本老年医学会学術集会. web開催. 2020年8月
    1. 藤田 康介, 井上 愛子, 宇野 千晴, 黄 継賢, 梅垣 宏行, 大西 丈二, 葛谷 雅文; 地域在住高齢者における、放送メディアを活用した非監視下プログラムの効果　名古屋大学TENG-projectより. 第30回日本老年医学会東海地方会. 名古屋. 2019年10月
    1. 藤田 康介, 田中 伸弥, 加古 誠人, 柴田 篤志, 中嶋 宏貴, 西田 佳宏, 葛谷 雅文; Short Physical Performance Batteryは75歳以上の入院期高齢患者の生命予後予測に有用である. 第61回日本老年医学会学術集会. 仙台. 2019年6月


---

## 受賞
  1. 豊秋奨学
  1. 特に優れた成績による奨学金返還免除, 日本学生支援機構, 半額免除. 2016


---

## 課外活動
  - Reviewer
    - Geriatrics & Gerontology International, 2020